name-template: "v$RESOLVED_VERSION 🌈 Service Release"
tag-template: "v$RESOLVED_VERSION"
categories:
    - title: "🚀 Feature(s)"
      collapse-after: 5
      labels:
          - "feature"
          - "enhancement"
    - title: "🐛 Bug Fixes"
      collapse-after: 3
      labels:
          - "fix"
          - "bugfix"
          - "bug"
    - title: "🧰 Maintenance"
      collapse-after: 1
      labels: 
          - "chore"
          - "documentation"
    - title: "⬆️ Dependencies"
      collapse-after: 1
      labels:
          - "dependencies"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' 
version-resolver:
    major:
        labels:
            - "major"
    minor:
        labels:
            - "minor"
    patch:
        labels:
            - "patch"
    default: patch
template: |
    ## What's Changed
    $CHANGES
