name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-to-lambda:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22.6'

    - name: Install dependencies
      run: go mod tidy

    - name: Build the Go binary
      run: GOOS=linux go build -o bootstrap main.go

    - name: Zip the binary
      run: zip bootstrap.zip bootstrap

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4.0.2
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        role-session-name: ${{ secrets.AWS_ROLE_TO_ASSUME_NAME }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy to AWS Lambda
      env:
          LAMBDA_FUNCTION_NAME: ${{ secrets.AWS_LAMBDA_FUNCTION_NAME }}
      run: |
        aws lambda update-function-code --$LAMBDA_FUNCTION_NAME go-lambda-cicd --zip-file fileb://bootstrap.zip